workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

.build-base:
  image:
    name: registry.ulbricht.casa/docker-images/android-native-app:latest
    pull_policy: always
  before_script:
    - chmod +x ./gradlew
    - touch local.properties
    - mkdir -p /opt/secure
  cache:
    key: $CI_PROJECT_NAME
    paths:
      - .gradle
  tags:
    - runner-amd64

.ios-base:
  variables:
    PATH: /opt/homebrew/lib/ruby/gems/3.2.0/bin:/opt/homebrew/opt/ruby@3.2/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/opt/homebrew/bin
    KEYCHAIN_NAME: "login.keychain-db"
  tags:
    - runner-macos
  before_script:
    - touch $CI_PROJECT_DIR/local.properties
    - security list-keychains
    - security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
    - security set-keychain-settings -lut 3600 "$KEYCHAIN_NAME"

.android-base:
  extends:
    - .build-base
  script:
    - bundle update
    - bundle exec fastlane android ${TRACK}

stages:
  - lint
  - build
  - deploy-android
  - deploy-ios

lint-debug-app:
  stage: lint
  extends:
    - .build-base
  script:
    - ./gradlew -Pci --console=plain :androidApp:lintAnalyzeDebug -PbuildDir=build --no-daemon

lint-release-app:
  stage: lint
  extends:
    - .build-base
  script:
    - ./gradlew -Pci --console=plain :androidApp:lintAnalyzeRelease -PbuildDir=build --no-daemon

build-android-debug-app:
  stage: build
  extends:
    - .build-base
  script:
    - ./gradlew -Pci --console=plain :androidApp:bundleDebug -PbuildDir=build --no-daemon

read-secure-files:
  image: registry.gitlab.com/gitlab-org/cli:latest
  stage: lint
  script:
    - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_FQDN --api-protocol $CI_SERVER_PROTOCOL
    - glab -R $CI_PROJECT_PATH securefile download --all --output-dir=".secure_files"
  artifacts:
    paths:
      - $CI_PROJECT_DIR/.secure_files

build-android-release-app:
  stage: build
  extends:
    - .build-base
  needs:
    - lint-release-app
    - read-secure-files
  script:
    - ./gradlew -Pci --console=plain :androidApp:bundle -PbuildDir=build --no-daemon
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never

deploy-android-alpha-app:
  extends:
    - .android-base
  needs:
    - lint-release-app
    - read-secure-files
  variables:
    TRACK: alpha
  stage: deploy-android
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-android-beta-app:
  extends:
    - .android-base
  needs:
    - lint-release-app
    - read-secure-files
    - deploy-android-alpha-app
  variables:
    TRACK: beta
  stage: deploy-android
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-android-production-app:
  extends:
    - .android-base
  needs:
    - lint-release-app
    - read-secure-files
  variables:
    TRACK: release
  stage: deploy-android
  rules:
    - if: $CI_COMMIT_TAG

deploy-testflight:
  stage: deploy-ios
  extends:
    - .ios-base
  variables:
    FL_BUILD_NUMBER_BUILD_NUMBER: $CI_JOB_ID
    APP_VERSION: 1.0.0
  needs:
    - lint-release-app
    - read-secure-files
  script:
    - bundle update
    - bundle exec fastlane ios beta
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy-appstore:
  stage: deploy-ios
  extends:
    - .ios-base
  variables:
    FL_BUILD_NUMBER_BUILD_NUMBER: $CI_JOB_ID
    APP_VERSION: $CI_COMMIT_TAG
  needs:
    - lint-release-app
    - read-secure-files
  script:
    - bundle update
    - bundle exec fastlane ios production
  rules:
    - if: $CI_COMMIT_TAG